import jsPDF from "jspdf";

export interface TeeSheetData {
  eventTitle: string;
  date: string;
  courseName: string;
  pairings: {
    name: string;
    teeTime: string;
    players: string[];
  }[];
}

export function generateTeeSheetPDF(data: TeeSheetData): Buffer {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.text("Tee Sheet", 105, 20, { align: "center" });

  // Event details
  doc.setFontSize(12);
  doc.text(data.eventTitle, 105, 30, { align: "center" });
  doc.setFontSize(10);
  doc.text(`${data.courseName} - ${data.date}`, 105, 36, { align: "center" });

  // Table header
  let yPosition = 50;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Tee Time", 20, yPosition);
  doc.text("Group", 60, yPosition);
  doc.text("Players", 100, yPosition);

  // Pairings
  doc.setFont("helvetica", "normal");
  yPosition += 8;

  data.pairings.forEach((pairing) => {
    // Check if we need a new page
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }

    doc.text(pairing.teeTime || "TBD", 20, yPosition);
    doc.text(pairing.name, 60, yPosition);
    
    // Players list
    pairing.players.forEach((player, index) => {
      doc.text(`${index + 1}. ${player}`, 100, yPosition + index * 5);
    });

    yPosition += Math.max(pairing.players.length * 5, 8) + 3;
  });

  // Footer
  doc.setFontSize(8);
  doc.text("Generated by Golf Day OS", 105, 285, { align: "center" });

  return Buffer.from(doc.output("arraybuffer"));
}
